/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blackjack;

import java.util.*;
import org.apache.commons.lang3.tuple.Pair;


public class App {
    public static void main(String[] args) {
        List<Card> playingCards = instantiatePlayingCards();
        Dealer dealer = new Dealer();
        Player player = new Player();

        Pair<Card, List<Card>> playerFirstCard = player.assignNewCard(playingCards);
        playingCards = playerFirstCard.getRight();
        Pair<Card, List<Card>> dealerFirstCard = dealer.assignNewCard(playingCards);
        playingCards = dealerFirstCard.getRight();
        Pair<Card, List<Card>> playerSecondCard = player.assignNewCard(playingCards);
        playingCards = playerSecondCard.getRight();
        Pair<Card, List<Card>> dealerSecondCard = dealer.assignNewCard(playingCards);
        playingCards = dealerSecondCard.getRight();

        printCardSetup(playerFirstCard.getLeft(), playerSecondCard.getLeft(), dealerFirstCard.getLeft(), dealerSecondCard.getLeft());
        System.out.println("YOUR TOTAL COUNT: " + player.getTotalCountWithAceOptions());
        System.out.println("DEALER'S INITIAL COUNT: " + dealer.getFirstCardCount());

        Pair<List<Card>, Boolean> playerTurnResult = player.playTurn(playingCards);
        playingCards = playerTurnResult.getLeft();
        boolean playerBusted = playerTurnResult.getRight();

        if (!playerBusted) {
            playingCards = dealer.playTurn(playingCards, dealerSecondCard.getLeft(), player);
        } else {
            System.out.println("DEALER WINS!");
        }
    }

    private static List<Card> instantiatePlayingCards() {
        List<Card> playingCards = new ArrayList<>();
        for(int i = 0; i < 8; i++) {
            Deck deck = new Deck();
            playingCards.addAll(deck.getDeck());
        }
        Collections.shuffle(playingCards);
        return playingCards;
    }

    private static void printCardSetup(Card playerFirstCard, Card playerSecondCard, Card dealerFirstCard, Card dealerSecondCard) {
        System.out.println("DEALER'S FACE-UP CARD:  " + dealerFirstCard.toString());
        System.out.println("YOUR CARDS: " + playerFirstCard.toString() + ", " + playerSecondCard.toString());
    }
    
}
